let photoismViewMode='3d';
function renderPhotoism3DPicker(area){
 area.innerHTML='<section class="photoism3d"><div class="model-heading"><div><h2>PHOTOISM</h2><p>내부를 누르면 앞문이 열립니다. 확인할 부품을 선택해주세요.</p></div><button id="modelLegacy">기존 그림 보기</button></div><div class="model-toolbar" aria-label="키오스크 방향"><button data-view="front" aria-pressed="true">앞면</button><button data-view="inside" aria-pressed="false">내부</button></div><h3 id="modelPartHeading" class="model-view-status" role="status" aria-live="polite">앞면 부품</h3><div class="model-stage model-callout-stage"><div id="photoismModelHost" class="model-host"></div><svg class="model-leaders" aria-hidden="true"></svg><div class="model-parts" aria-label="진단할 부품 선택"></div><div class="model-cms-satellite" aria-hidden="true"><svg viewBox="25 12 250 80" aria-hidden="true"><g>        <rect x="90" y="63" width="24" height="6" fill="#3a3d47"/>        <rect x="186" y="63" width="24" height="6" fill="#3a3d47"/>        <rect x="34" y="52" width="56" height="30" rx="3" fill="#1c2a3a" stroke="#3a5a78" stroke-width="1.2"/>        <rect x="210" y="52" width="56" height="30" rx="3" fill="#1c2a3a" stroke="#3a5a78" stroke-width="1.2"/>        <g stroke="#3a5a78" stroke-width="1">          <line x1="48" y1="52" x2="48" y2="82"/><line x1="62" y1="52" x2="62" y2="82"/><line x1="76" y1="52" x2="76" y2="82"/>          <line x1="224" y1="52" x2="224" y2="82"/><line x1="238" y1="52" x2="238" y2="82"/><line x1="252" y1="52" x2="252" y2="82"/>        </g>        <rect x="120" y="50" width="60" height="36" rx="9" fill="#2c2f38" stroke="#454852" stroke-width="1.5"/>        <circle class="sat-blink" cx="150" cy="68" r="4"/>        <path d="M132,50 Q150,20 168,50 Z" fill="#454852" stroke="#5a5d68" stroke-width="1.2"/>        <line x1="150" y1="34" x2="150" y2="20" stroke="#5a5d68" stroke-width="2"/>        <circle cx="150" cy="18" r="3" fill="#5a5d68"/>        </g></svg></div><svg class="model-cms-leader" aria-hidden="true"><path></path><circle r="3"></circle></svg><button class="model-callout model-cms-label">CMS</button><svg class="model-cms-waves" aria-hidden="true"><path></path><path></path><path></path></svg></div></section>';
 document.getElementById('breadcrumb').textContent='포토이즘 · 부품 선택';
 const host=area.querySelector('#photoismModelHost'),parts=area.querySelector('.model-parts'),heading=area.querySelector('#modelPartHeading'),stage=area.querySelector('.model-stage'),lines=area.querySelector('.model-leaders');let viewer=null,version=0,failed=false,active=[];
 const groups={front:[['에스라이트','카메라','모니터','지폐투입기'],['지속광','리모컨','카드리더기']],inside:[['PC','서비스코인 / 설정'],['프린터']]};
 function calloutInset(){return Math.min(56,Math.max(4,(host.clientWidth-400)*.14));}
 function layoutSignal(){if(failed||!viewer)return;const svg=area.querySelector(".model-cms-waves"),button=area.querySelector(".model-cms-satellite"),w=host.clientWidth,h=host.clientHeight;svg.setAttribute("viewBox",`0 0 ${w} ${h}`);const inset=calloutInset(),label=area.querySelector(".model-cms-label"),leader=area.querySelector(".model-cms-leader");button.style.right=(12+inset)+"px";label.style.right=(4+inset)+"px";label.style.top=(button.offsetTop+button.offsetHeight+10)+"px";leader.setAttribute("viewBox",`0 0 ${w} ${h}`);const ax=button.offsetLeft+button.offsetWidth*.5,ay=button.offsetTop+button.offsetHeight*.62,bx=label.offsetLeft+label.offsetWidth*.5,by=label.offsetTop;leader.querySelector("path").setAttribute("d",`M ${bx} ${by} L ${bx} ${by-8} L ${ax} ${ay}`);leader.querySelector("circle").setAttribute("cx",ax);leader.querySelector("circle").setAttribute("cy",ay);const x=button.offsetLeft+button.offsetWidth*.42,y=button.offsetTop+button.offsetHeight*.65,p=viewer.project("카메라"),dx=p.x-x,dy=p.y-y,len=Math.hypot(dx,dy);if(!len)return;const ux=dx/len,uy=dy/len;svg.querySelectorAll("path").forEach((path,i)=>{const t=.17+i*.19,cx=x+dx*t,cy=y+dy*t,r=8+i*6;path.setAttribute("d",`M ${cx-uy*r-ux*3} ${cy+ux*r-uy*3} Q ${cx+ux*8} ${cy+uy*8} ${cx+uy*r-ux*3} ${cy-ux*r-uy*3}`);});}
 function layout(){layoutSignal();if(failed||!viewer||!active.length)return;const w=host.clientWidth,h=host.clientHeight;lines.setAttribute('viewBox',`0 0 ${w} ${h}`);for(const side of [0,1]){const list=active.filter(a=>a.side===side);const ys=list.map(a=>viewer.project(a.name).y);for(let i=0;i<ys.length;i++)ys[i]=Math.max(28,ys[i],i?ys[i-1]+57:0);if(ys.at(-1)>h-28){ys[ys.length-1]=h-28;for(let i=ys.length-2;i>=0;i--)ys[i]=Math.min(ys[i],ys[i+1]-57);}list.forEach((a,i)=>{const p=viewer.project(a.name),bw=a.button.offsetWidth,y=ys[i],x=side?w-bw-4-calloutInset():4+calloutInset();a.button.style.left=x+'px';a.button.style.top=(y-22)+'px';const start=side?x:x+bw,elbow=side?Math.max(p.x+12,start-18):Math.min(p.x-12,start+18);a.path.setAttribute('d',`M ${start} ${y} L ${elbow} ${y} L ${p.x} ${p.y}`);a.dot.setAttribute('cx',p.x);a.dot.setAttribute('cy',p.y);});}}
 function reveal(mode,token){if(!host.isConnected||token!==version)return;heading.textContent=mode==='front'?'앞面 부품 선택'.replace('面','면'):'내부 부품 선택';parts.replaceChildren();lines.replaceChildren();active=[];let n=0;groups[mode].forEach((names,side)=>names.forEach(name=>{const i=n++,button=document.createElement('button');button.className='model-callout';button.textContent=name;button.style.setProperty('--callout-delay',(i*65+180)+'ms');if(name==='서비스코인 / 설정'){button.style.whiteSpace='normal';button.style.wordBreak='keep-all';}button.onclick=()=>selectDeviceFromPicker(name==='서비스코인 / 설정'?'서비스코인':name);parts.appendChild(button);const g=document.createElementNS('http://www.w3.org/2000/svg','g'),path=document.createElementNS(g.namespaceURI,'path'),dot=document.createElementNS(g.namespaceURI,'circle');g.style.setProperty('--callout-delay',(i*65)+'ms');path.setAttribute('pathLength','1');dot.setAttribute('r','3');g.append(path,dot);lines.appendChild(g);active.push({name,side,button,path,dot});}));parts.removeAttribute('aria-busy');layout();}
 function change(mode){const token=++version;active=[];parts.replaceChildren();lines.replaceChildren();parts.setAttribute('aria-busy','true');heading.textContent=mode==='front'?'앞문을 닫는 중…':'앞문을 여는 중…';area.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===mode)));if(failed)reveal(mode,token);else viewer.view(mode,()=>reveal(mode,token));}
 area.querySelector('#modelLegacy').onclick=()=>{version++;photoismViewMode='2d';viewer?.dispose();renderPickerScreen();};
 area.querySelector('.model-cms-label').onclick=()=>selectDeviceFromPicker('CMS');
 function fallback(){failed=true;viewer?.dispose();stage.classList.add('model-callout-fallback');host.innerHTML='<div class="model-unavailable">3D 표시를 사용할 수 없습니다.<br>부품 메뉴 또는 기존 그림 보기를 이용해주세요.</div>';}
 host.addEventListener('modelrender',layout);
 host.addEventListener('modelerror',()=>{if(!host.isConnected)return;fallback();reveal(area.querySelector('[data-view][aria-pressed="true"]').dataset.view,version);},{once:true});
 try{viewer=PhotoismModel.mount(host);}catch(error){fallback();}
 area.querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>change(button.dataset.view));change('front');loadRecentSymptoms('photoism');
}
