let photoismViewMode='3d';
function renderPhotoism3DPicker(area){
 area.innerHTML='<section class="photoism3d"><div class="model-heading"><div><h2>PHOTOISM</h2><p>앞면 또는 뒷면을 고르고, 부품을 가리키는 항목을 눌러주세요.</p></div><button id="modelLegacy">기존 그림 보기</button></div><div class="model-toolbar" aria-label="키오스크 방향"><button data-view="front" aria-pressed="true">앞면</button><button data-view="inside" aria-pressed="false">뒷면</button></div><h3 id="modelPartHeading" class="model-view-status" role="status" aria-live="polite">앞면 부품</h3><div class="model-stage model-callout-stage"><div id="photoismModelHost" class="model-host"></div><svg class="model-leaders" aria-hidden="true"></svg><div class="model-parts" aria-label="진단할 부품 선택"></div></div><div class="model-common" aria-label="공통 메뉴"></div></section>';
 document.getElementById('breadcrumb').textContent='포토이즘 · 부품 선택';
 const host=area.querySelector('#photoismModelHost'),parts=area.querySelector('.model-parts'),heading=area.querySelector('#modelPartHeading'),stage=area.querySelector('.model-stage'),lines=area.querySelector('.model-leaders');let viewer=null,version=0,failed=false,active=[];
 const groups={front:[['에스라이트','카메라','모니터','서비스코인'],['지속광','리모컨','지폐투입기','카드리더기']],inside:[['프린터'],['PC']]};
 function layout(){if(failed||!viewer||!active.length)return;const w=host.clientWidth,h=host.clientHeight;lines.setAttribute('viewBox',`0 0 ${w} ${h}`);for(const side of [0,1]){const list=active.filter(a=>a.side===side);const ys=list.map(a=>viewer.project(a.name).y);for(let i=0;i<ys.length;i++)ys[i]=Math.max(28,ys[i],i?ys[i-1]+57:0);if(ys.at(-1)>h-28){ys[ys.length-1]=h-28;for(let i=ys.length-2;i>=0;i--)ys[i]=Math.min(ys[i],ys[i+1]-57);}list.forEach((a,i)=>{const p=viewer.project(a.name),bw=a.button.offsetWidth,y=ys[i],x=side?w-bw-4:4;a.button.style.left=x+'px';a.button.style.top=(y-22)+'px';const start=side?x:x+bw,elbow=side?Math.max(p.x+12,start-18):Math.min(p.x-12,start+18);a.path.setAttribute('d',`M ${start} ${y} L ${elbow} ${y} L ${p.x} ${p.y}`);a.dot.setAttribute('cx',p.x);a.dot.setAttribute('cy',p.y);});}}
 function reveal(mode,token){if(!host.isConnected||token!==version)return;heading.textContent=mode==='front'?'앞面 부품 선택'.replace('面','면'):'뒷면 부품 선택';parts.replaceChildren();lines.replaceChildren();active=[];let n=0;groups[mode].forEach((names,side)=>names.forEach(name=>{const i=n++,button=document.createElement('button');button.className='model-callout';button.textContent=name;button.style.setProperty('--callout-delay',(i*65+180)+'ms');button.onclick=()=>selectDeviceFromPicker(name);parts.appendChild(button);const g=document.createElementNS('http://www.w3.org/2000/svg','g'),path=document.createElementNS(g.namespaceURI,'path'),dot=document.createElementNS(g.namespaceURI,'circle');g.style.setProperty('--callout-delay',(i*65)+'ms');path.setAttribute('pathLength','1');dot.setAttribute('r','3');g.append(path,dot);lines.appendChild(g);active.push({name,side,button,path,dot});}));parts.removeAttribute('aria-busy');layout();}
 function change(mode){const token=++version;active=[];parts.replaceChildren();lines.replaceChildren();parts.setAttribute('aria-busy','true');heading.textContent=mode==='front'?'앞면으로 전환 중…':'뒷면으로 전환 중…';area.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===mode)));if(failed)reveal(mode,token);else viewer.view(mode,()=>reveal(mode,token));}
 area.querySelector('#modelLegacy').onclick=()=>{version++;photoismViewMode='2d';viewer?.dispose();renderPickerScreen();};
 for(const name of ['설정','CMS']){const button=document.createElement('button');button.textContent=name;button.onclick=()=>selectDeviceFromPicker(name);area.querySelector('.model-common').appendChild(button);}
 function fallback(){failed=true;viewer?.dispose();stage.classList.add('model-callout-fallback');host.innerHTML='<div class="model-unavailable">3D 표시를 사용할 수 없습니다.<br>부품 메뉴 또는 기존 그림 보기를 이용해주세요.</div>';}
 host.addEventListener('modelrender',layout);
 host.addEventListener('modelerror',()=>{if(!host.isConnected)return;fallback();reveal(area.querySelector('[data-view][aria-pressed="true"]').dataset.view,version);},{once:true});
 try{viewer=PhotoismModel.mount(host);}catch(error){fallback();}
 area.querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>change(button.dataset.view));change('front');loadRecentSymptoms('photoism');
}
